Update stripe-js for Custom Checkout types
stripe/react-stripe-js pull request #479
Opened 2024-03-04 20:09 UTC by danwang-stripe

### Summary & motivation
Update version of stripe-js to [v3.0.7](https://github.com/stripe/stripe-js/releases/tag/v3.0.7) to pull in new Custom Checkout types

### API review

Copy [this template] **or** link to an API review issue.

[this template]:
  https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md

### Testing & documentation

2024-03-04 20:53 UTC, madhav-stripe requested changes

2024-03-04 20:53 UTC, madhav-stripe commented on package.json
> +    "rollup": "^4.12.0",
@danwang-stripe I don't think we can upgrade rollup in this PR

2024-03-04 21:41 UTC, madhav-stripe commented
r? @fruchtose-stripe

2024-03-05 18:27 UTC, madhav-stripe commented
build output on current master:

```
-rw-r--r--  1 madhav  staff  44871 Mar  5 10:25 react-stripe.d.ts
-rw-r--r--  1 madhav  staff  44871 Mar  5 10:25 react-stripe.esm.d.ts
-rw-r--r--  1 madhav  staff  41327 Mar  5 10:25 react-stripe.esm.js
-rw-r--r--  1 madhav  staff  42399 Mar  5 10:25 react-stripe.js
-rw-r--r--  1 madhav  staff  44871 Mar  5 10:25 react-stripe.umd.d.ts
-rw-r--r--  1 madhav  staff  46976 Mar  5 10:25 react-stripe.umd.js
-rw-r--r--  1 madhav  staff  44871 Mar  5 10:25 react-stripe.umd.min.d.ts
-rw-r--r--  1 madhav  staff  16435 Mar  5 10:25 react-stripe.umd.min.js
```

2024-03-08 18:42 UTC, danwang-stripe commented
r? @madhav-stripe 

Merged master in with 776705b085f9daa3c045a0a1da06326266e7d3e7

Thanks for helping with the dependency upgrades!

2024-03-08 18:53 UTC, madhav-stripe approved these changes

2024-03-08 18:53 UTC, merged